In [4]:
import pandas as pd

In [5]:
def leer_precios(filename):
    for k in range(10):
        df = pd.read_excel(filename,
                           skiprows = k,
                           usecols = list(range(26)))
        if df.iloc[0,0] == 'Fecha':
            df = pd.read_excel(filename,
                               skiprows = k+1,
                               usecols = list(range(26)))
            break
        
    return(df)

In [19]:
filenames = !ls precios/*
dfs = []
for filename in filenames:
    dfs.append(leer_precios(filename))
dfs = pd.concat(dfs, sort=True)
dfs.size

218634

In [17]:
dfs.shape

(8409, 26)

In [18]:
dfs

,0,1,10,11,12,13,14,15,16,17,...,23,3,4,5,6,7,8,9,Fecha,Version
0,NaN,1.073000,2.827000,2.827000,2.827000,1.074000,1.073000,1.073000,1.073000,1.073000,...,1.073000,1.073000,1.073000,1.073000,1.073000,1.073000,1.074000,1.074000,1995-07-20,NaN
1,1.073000,1.000000,6.000000,9.256000,9.256000,5.000000,5.000000,1.000000,1.000000,5.000000,...,1.000000,1.000000,1.000000,1.000000,5.000000,6.000000,6.000000,6.000000,1995-07-21,NaN
2,1.073000,1.073000,1.303000,1.303000,1.303000,1.303000,1.073000,1.000000,1.000000,1.000000,...,1.073000,1.000000,1.000000,1.073000,1.303000,1.303000,1.303000,1.303000,1995-07-22,NaN
3,1.073000,1.000000,1.000000,1.000000,1.238000,1.238000,1.000000,0.100000,0.100000,1.000000,...,1.000000,1.000000,1.000000,1.000000,0.100000,1.000000,1.000000,1.000000,1995-07-23,NaN
4,1.000000,1.000000,8.845000,9.256000,3.000000,1.073000,1.073000,1.073000,3.000000,2.000000,...,1.000000,1.000000,1.000000,1.073000,3.000000,3.000000,3.000000,3.500000,1995-07-24,NaN
5,0.990000,0.990000,1.263000,1.263000,1.263000,1.073000,1.073000,1.073000,1.073000,1.073000,...,0.990000,0.990000,0.990000,1.073000,1.263000,1.263000,1.263000,1.263000,1995-07-25,NaN
6,0.500000,0.500000,1.073000,1.073000,1.073000,0.990000,0.500000,0.500000,0.990000,0.990000,...,0.000000,0.500000,0.500000,0.990000,1.073000,1.073000,1.073000,1.073000,1995-07-26,NaN
7,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,...,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,0.500000,1995-07-27,NaN
8,0.000000,0.000000,1.073000,1.073000,0.463000,0.463000,0.463000,0.463000,0.463000,0.463000,...,0.000000,0.000000,0.000000,0.463000,0.463000,1.000000,0.463000,0.463000,1995-07-28,NaN
9,1.000000,1.000000,1.070000,1.070000,1.072000,1.070000,1.070000,1.070000,1.070000,1.070000,...,1.070000,0.000000,1.000000,0.000000,1.070000,1.070000,1.070000,1.070000,1995-07-29,NaN
10,1.072000,1.000000,1.072000,1.072000,1.073000,1.072000,1.000000,0.000000,0.000000,0.100000,...,0.000000,0.000000,0.000000,0.000000,0.100000,1.000000,1.072000,1.072000,1995-07-30,NaN
11,0.000000,0.000000,0.000000,0.000000,1.070000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,1.000000,1.073000,0.000000,0.000000,0.100000,1995-07-31,NaN
12,0.000000,0.000000,1.070000,1.070000,1.070000,1.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,1.070000,1.073000,0.000000,1.070000,17.000000,1995-08-01,NaN
13,1.073000,1.073000,1.073000,1.073000,1.073000,1.100000,1.073000,1.073000,1.100000,1.073000,...,1.073000,1.073000,1.073000,1.073000,1.100000,1.073000,1.073000,1.073000,1995-08-02,NaN
14,1.073000,1.073000,2.000000,2.000000,2.000000,1.073000,1.073000,1.073000,1.500000,1.073000,...,1.073000,1.073000,1.073000,1.100000,2.000000,2.000000,2.000000,2.000000,1995-08-03,NaN
15,1.073000,1.073000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,2.000000,...,1.500000,1.073000,1.073000,2.000000,2.000000,2.000000,2.000000,2.000000,1995-08-04,NaN
16,2.000000,2.000000,2.558000,2.558000,2.558000,2.558000,2.500000,2.500000,2.500000,2.500000,...,2.500000,1.073000,2.000000,2.500000,2.500000,2.558000,2.558000,2.558000,1995-08-05,NaN
17,3.000000,1.073000,3.000000,3.000000,3.000000,3.000000,3.000000,1.070000,1.070000,1.000000,...,1.070000,1.073000,1.073000,3.000000,3.000000,3.000000,3.200000,3.000000,1995-08-06,NaN
18,3.000000,3.000000,3.900000,3.700000,3.700000,3.700000,3.500000,3.500000,3.500000,3.500000,...,3.000000,1.073000,3.000000,3.000000,3.500000,3.500000,3.700000,3.700000,1995-08-07,NaN
19,3.000000,3.000000,7.000000,8.000000,8.000000,7.000000,7.000000,7.000000,7.000000,7.000000,...,5.800000,3.000000,5.800000,7.000000,7.000000,9.000000,8.000000,7.000000,1995-08-08,NaN
20,10.000000,10.000000,18.000000,18.000000,17.500000,13.788000,13.788000,13.788000,13.788000,13.788000,...,12.000000,10.000000,10.000000,13.788000,17.000000,15.000000,15.000000,13.788000,1995-08-09,NaN
21,18.000000,18.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,21.000000,...,18.000000,18.000000,18.000000,18.000000,21.000000,21.000000,21.000000,21.000000,1995-08-10,NaN
22,12.000000,6.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,25.000000,...,6.000000,6.000000,22.600000,25.000000,25.000000,25.000000,25.000000,25.000000,1995-08-11,NaN
23,30.000000,15.000000,32.500000,40.000000,40.000000,39.492000,31.000000,31.000000,31.000000,31.000000,...,30.000000,15.000000,17.500000,30.000000,30.000000,31.000000,40.000000,31.000000,1995-08-12,NaN
24,35.000000,18.000000,40.000000,40.000000,40.000000,40.000000,40.000000,39.492000,39.492000,39.492000,...,23.300000,18.000000,18.000000,24.600000,32.000000,39.492000,40.000000,40.000000,1995-08-13,NaN
25,17.000000,1.074000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,40.000000,...,17.500000,12.000000,17.500000,39.492000,40.000000,40.000000,40.000000,40.000000,1995-08-14,NaN
26,1.074000,1.074000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,20.000000,...,1.074000,1.074000,1.074000,17.500000,20.000000,20.000000,20.000000,20.000000,1995-08-15,NaN
27,1.074000,1.074000,17.500000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,8.000000,...,1.074000,1.074000,1.074000,8.000000,12.000000,8.000000,12.000000,15.000000,1995-08-16,NaN
28,1.000000,1.000000,2.000000,2.000000,2.000000,1.074000,1.074000,1.074000,1.074000,1.074000,...,1.074000,1.000000,1.074000,2.000000,2.000000,2.000000,2.000000,2.000000,1995-08-17,NaN
29,1.075000,1.075000,2.000000,2.000000,2.000000,2.000000,1.075000,1.075000,2.000000,2.000000,...,1.075000,1.075000,1.075000,2.000000,2.000000,2.000000,2.000000,2.000000,1995-08-18,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95,95.061224,95.061224,121.061224,121.061224,121.061224,121.061224,121.061224,121.061224,121.061224,119.061224,...,101.061224,61.457224,101.061224,101.061224,101.061224,101.061224,117.061224,119.061224,2018-04-06,TXR
96,114.248319,114.248319,121.248319,121.248319,121.248319,121.248319,121.248319,121.248319,121.248319,121.048319,...,115.247319,114.248319,114.248319,114.248319,114.248319,114.248319,121.048319,121.248319,2018-04-07,TXR
97,95.955346,94.955346,104.855346,104.855346,104.855346,104.855346,104.855346,104.855346,104.855346,104.855346,...,104.855346,94.955346,95.955346,95.955346,83.955346,95.955346,95.955346,95.955346,2018-04-08,TXR
98,61.546254,61.546254,110.150254,145.150254,110.150254,110.150254,145.150254,145.150254,123.126254,110.150254,...,96.150254,61.546254,61.546254,96.150254,96.150254,96.150254,96.150254,110.150254,2018-04-09,TXR
99,96.544901,96.544901,117.544901,117.544901,117.544901,129.544901,129.544901,129.544901,117.544901,117.544901,...,96.544901,85.544901,96.544901,96.544901,96.544901,96.544901,115.544901,115.544901,2018-04-10,TXR
100,95.951640,95.951640,182.951640,182.951640,182.951640,182.951640,182.951640,182.951640,182.951640,119.065640,...,95.951640,95.951640,97.951640,119.065640,119.065640,119.065640,142.951640,142.951640,2018-04-11,TXR
101,85.050235,85.050235,128.050235,128.050235,128.050235,128.050235,128.050235,128.050235,123.026235,115.050235,...,104.050235,84.050235,85.050235,104.050235,104.050235,115.050235,110.050235,110.050235,2018-04-12,TXR
102,95.019470,95.019470,119.135470,122.995470,119.135470,119.135470,165.019470,119.135470,119.135470,119.135470,...,115.019470,95.019470,95.019470,110.019470,115.019470,115.019470,119.135470,119.135470,2018-04-13,TXR
103,112.019146,112.019146,112.536146,112.536146,112.536146,112.536146,112.536146,112.536146,112.536146,112.536146,...,112.536146,112.019146,112.019146,112.536146,112.019146,112.536146,112.536146,112.536146,2018-04-14,TXR
104,102.413184,102.413184,102.413184,103.913184,103.913184,103.913184,103.913184,103.913184,102.413184,102.413184,...,102.413184,84.413184,84.413184,84.413184,83.413184,84.413184,102.413184,102.413184,2018-04-15,TXR
105,81.128662,81.128662,126.128662,126.128662,206.128662,126.128662,155.128662,155.128662,155.128662,126.128662,...,84.128662,74.128662,81.128662,83.128662,84.128662,126.128662,126.128662,126.128662,2018-04-16,TXR
106,103.310629,103.310629,165.310629,125.310629,125.310629,125.310629,125.310629,125.310629,125.310629,125.310629,...,82.310629,103.310629,103.310629,125.310629,125.310629,125.310629,130.310629,130.310629,2018-04-17,TXR
107,77.397910,77.397910,197.397910,137.397910,137.397910,137.397910,197.397910,197.397910,137.397910,115.397910,...,115.397910,100.397910,100.397910,115.397910,115.397910,125.897910,137.397910,137.397910,2018-04-18,TXR
108,130.148787,78.148787,141.148787,141.148787,141.148787,141.148787,141.148787,141.148787,141.148787,134.648787,...,130.148787,78.148787,78.148787,130.148787,130.148787,130.148787,134.648787,134.648787,2018-04-19,TXR
109,73.651514,70.651514,138.651514,175.651514,138.651514,138.651514,175.651514,175.651514,138.651514,110.651514,...,73.651514,73.651514,70.651514,85.651514,110.651514,85.651514,134.651514,134.651514,2018-04-20,TXR
110,73.040902,72.940902,83.940902,84.940902,84.940902,84.940902,83.940902,83.940902,80.340902,73.040902,...,73.040902,72.940902,72.940902,72.940902,72.940902,73.040902,73.040902,80.340902,2018-04-21,TXR
111,73.182921,73.082921,73.182921,73.182921,73.182921,73.182921,73.182921,73.182921,73.182921,73.182921,...,73.182921,73.082921,67.082921,67.082921,66.582921,73.082921,73.182921,73.182921,2018-04-22,TXR
112,89.952904,89.952904,134.952904,142.952904,134.952904,142.952904,135.952904,135.952904,134.952904,134.952904,...,117.952904,89.952904,89.952904,89.952904,104.952904,129.952904,134.952904,134.952904,2018-04-23,TXR
113,124.376789,102.376789,149.376789,150.376789,149.376789,149.376789,149.376789,149.376789,147.376789,147.376789,...,124.376789,92.376789,102.376789,124.376789,124.376789,130.276789,147.376789,147.376789,2018-04-24,TXR
114,78.515851,77.515851,144.515851,147.515851,147.515851,144.515851,144.515851,144.515851,144.515851,144.515851,...,140.515851,77.515851,78.515851,110.515851,115.515851,140.515851,140.515851,147.515851,2018-04-25,TXR
115,72.752131,72.752131,132.752131,132.752131,132.752131,132.752131,132.752131,132.752131,132.752131,132.752131,...,72.752131,72.752131,72.752131,76.752131,109.752131,111.752131,111.752131,132.752131,2018-04-26,TXR
116,71.669496,71.669496,126.669496,126.669496,126.669496,126.669496,126.669496,126.669496,126.669496,106.668496,...,71.669496,71.669496,71.669496,71.669496,71.669496,74.669496,106.668496,106.668496,2018-04-27,TXR
117,70.008969,70.008969,120.008969,120.008969,120.008969,119.008969,85.008969,85.008969,73.008969,73.008969,...,70.008969,70.008969,70.008969,70.008969,70.008969,70.008969,85.008969,85.008969,2018-04-28,TXR
118,70.012686,70.012686,70.012686,73.012686,73.012686,73.012686,73.012686,70.012686,70.012686,70.012686,...,70.012686,66.508686,66.508686,66.508686,66.508686,66.508686,70.012686,70.012686,2018-04-29,TXR
119,67.645951,67.645951,142.645951,145.645951,142.645951,142.645951,145.645951,145.645951,85.645951,90.645951,...,67.645951,67.645951,67.645951,68.645951,68.645951,73.645951,85.645951,85.645951,2018-04-30,TXR
120,64.229226,64.229226,71.229226,81.229226,81.229226,71.229226,71.229226,71.229226,69.229226,81.229226,...,64.229226,64.129226,64.129226,64.129226,64.129226,64.229226,64.229226,69.229226,2018-05-01,TX2
121,63.332816,63.332816,80.832816,83.832816,83.832816,83.832816,83.832816,83.832816,80.832816,80.832816,...,67.832816,63.332816,63.332816,64.332816,67.832816,79.831816,80.832816,80.832816,2018-05-02,TX2
122,63.710848,64.210848,78.710848,79.710848,78.710848,78.710848,79.710848,79.710848,79.710848,67.710848,...,63.710848,61.710848,63.710848,64.210848,64.210848,67.710848,67.710848,67.710848,2018-05-03,TX1
123,61.543453,61.543453,65.543453,65.543453,65.543453,65.543453,65.543453,65.543453,65.543453,65.543453,...,64.043453,61.543453,61.543453,65.543453,61.543453,64.043453,65.543453,65.543453,2018-05-04,TX1
124,73.742918,73.742918,75.242918,75.242918,75.242918,75.242918,73.742918,73.742918,75.242918,73.742918,...,75.242918,70.242918,70.242918,70.242918,73.742918,73.742918,75.242918,75.242918,2018-05-05,TX1

In [20]:
dfs1 = pd.melt(dfs,id_vars='Fecha')

In [21]:
dfs1

             Fecha variable  value
0       1995-07-20        0    NaN
1       1995-07-21        0  1.073
2       1995-07-22        0  1.073
3       1995-07-23        0  1.073
4       1995-07-24        0      1
5       1995-07-25        0   0.99
6       1995-07-26        0    0.5
7       1995-07-27        0    0.5
8       1995-07-28        0      0
9       1995-07-29        0      1
10      1995-07-30        0  1.072
11      1995-07-31        0      0
12      1995-08-01        0      0
13      1995-08-02        0  1.073
14      1995-08-03        0  1.073
15      1995-08-04        0  1.073
16      1995-08-05        0      2
17      1995-08-06        0      3
18      1995-08-07        0      3
19      1995-08-08        0      3
20      1995-08-09        0     10
21      1995-08-10        0     18
22      1995-08-11        0     12
23      1995-08-12        0     30
24      1995-08-13        0     35
25      1995-08-14        0     17
26      1995-08-15        0  1.074
27      1995-08-16        0  1.074
28      1995-08-17        0      1
29      1995-08-18        0  1.075
...            ...      ...    ...
210195  2018-04-06  Version    TXR
210196  2018-04-07  Version    TXR
210197  2018-04-08  Version    TXR
210198  2018-04-09  Version    TXR
210199  2018-04-10  Version    TXR
210200  2018-04-11  Version    TXR
210201  2018-04-12  Version    TXR
210202  2018-04-13  Version    TXR
210203  2018-04-14  Version    TXR
210204  2018-04-15  Version    TXR
210205  2018-04-16  Version    TXR
210206  2018-04-17  Version    TXR
210207  2018-04-18  Version    TXR
210208  2018-04-19  Version    TXR
210209  2018-04-20  Version    TXR
210210  2018-04-21  Version    TXR
210211  2018-04-22  Version    TXR
210212  2018-04-23  Version    TXR
210213  2018-04-24  Version    TXR
210214  2018-04-25  Version    TXR
210215  2018-04-26  Version    TXR
210216  2018-04-27  Version    TXR
210217  2018-04-28  Version    TXR
210218  2018-04-29  Version    TXR
210219  2018-04-30  Version    TXR
210220  2018-05-01  Version    TX2
210221  2018-05-02  Version    TX2
210222  2018-05-03  Version    TX1
210223  2018-05-04  Version    TX1
210224  2018-05-05  Version    TX1

[210225 rows x 3 columns]

In [22]:
dfs1.to_csv("resumen.csv")